name: challenge_mobile_multi
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  cupertino_icons: ^1.0.6
  dio: ^5.8.0+1
  flutter_svg: ^2.0.17
  lottie: ^3.3.1
  provider: ^6.1.4
  flutter_dotenv: ^5.2.1
  get_it: ^8.0.3
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.1
  shared_preferences: ^2.5.3
  cached_network_image: ^3.4.1
  youtube_player_flutter: ^9.1.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/lottie/
    - lib/l10n/
    - .env

  fonts:
    - family: Montserrat-Thin
      fonts:
        - asset: fonts/Montserrat-Thin.ttf
    - family: Montserrat-ThinItalic
      fonts:
        - asset: fonts/Montserrat-ThinItalic.ttf

    - family: Montserrat-ExtraLight
      fonts:
        - asset: fonts/Montserrat-ExtraLight.ttf
    - family: Montserrat-ExtraLightItalic
      fonts:
        - asset: fonts/Montserrat-ExtraLightItalic.ttf

    - family: Montserrat-Light
      fonts:
        - asset: fonts/Montserrat-Light.ttf
    - family: Montserrat-LightItalic
      fonts:
        - asset: fonts/Montserrat-LightItalic.ttf

    - family: Montserrat-Regular
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
    - family: Montserrat-Italic
      fonts:
        - asset: fonts/Montserrat-Italic.ttf

    - family: Montserrat-Medium
      fonts:
        - asset: fonts/Montserrat-Medium.ttf
    - family: Montserrat-MediumItalic
      fonts:
        - asset: fonts/Montserrat-MediumItalic.ttf

    - family: Montserrat-SemiBold
      fonts:
        - asset: fonts/Montserrat-SemiBold.ttf
    - family: Montserrat-SemiBoldItalic
      fonts:
        - asset: fonts/Montserrat-SemiBoldItalic.ttf

    - family: Montserrat-Bold
      fonts:
        - asset: fonts/Montserrat-Bold.ttf
    - family: Montserrat-BoldItalic
      fonts:
        - asset: fonts/Montserrat-BoldItalic.ttf

    - family: Montserrat-ExtraBold
      fonts:
        - asset: fonts/Montserrat-ExtraBold.ttf
    - family: Montserrat-ExtraBoldItalic
      fonts:
        - asset: fonts/Montserrat-ExtraBoldItalic.ttf

    - family: Montserrat-Black
      fonts:
        - asset: fonts/Montserrat-Black.ttf
    - family: Montserrat-BlackItalic
      fonts:
        - asset: fonts/Montserrat-BlackItalic.ttf