name: challenge_mobile_multi
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  dio: ^5.8.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Monstserrat-Thin
      fonts:
        - asset: fonts/Monstserrat-Thin.ttf
    - family: Monstserrat-ThinItalic
      fonts:
        - asset: fonts/Monstserrat-ThinItalic.ttf

    - family: Monstserrat-ExtraLight
      fonts:
        - asset: fonts/Monstserrat-ExtraLight.ttf
    - family: Monstserrat-ExtraLightItalic
      fonts:
        - asset: fonts/Monstserrat-ExtraLightItalic.ttf

    - family: Monstserrat-Light
      fonts:
        - asset: fonts/Monstserrat-Light.ttf
    - family: Monstserrat-LightItalic
      fonts:
        - asset: fonts/Monstserrat-LightItalic.ttf

    - family: Monstserrat-Regular
      fonts:
        - asset: fonts/Monstserrat-Regular.ttf
    - family: Monstserrat-Italic
      fonts:
        - asset: fonts/Monstserrat-Italic.ttf

    - family: Monstserrat-Medium
      fonts:
        - asset: fonts/Monstserrat-Medium.ttf
    - family: Monstserrat-MediumItalic
      fonts:
        - asset: fonts/Monstserrat-MediumItalic.ttf

    - family: Monstserrat-SemiBold
      fonts:
        - asset: fonts/Monstserrat-SemiBold.ttf
    - family: Monstserrat-SemiBoldItalic
      fonts:
        - asset: fonts/Monstserrat-SemiBoldItalic.ttf

    - family: Monstserrat-Bold
      fonts:
        - asset: fonts/Monstserrat-Bold.ttf
    - family: Monstserrat-BoldItalic
      fonts:
        - asset: fonts/Monstserrat-BoldItalic.ttf

    - family: Monstserrat-ExtraBold
      fonts:
        - asset: fonts/Monstserrat-ExtraBold.ttf
    - family: Monstserrat-ExtraBoldItalic
      fonts:
        - asset: fonts/Monstserrat-ExtraBoldItalic.ttf

    - family: Monstserrat-Black
      fonts:
        - asset: fonts/Monstserrat-Black.ttf
    - family: Monstserrat-BlackItalic
      fonts:
        - asset: fonts/Monstserrat-BlackItalic.ttf
  
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
